# Generated by Django 4.2.5 on 2023-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_amigo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='nome',
        ),
        migrations.AddField(
            model_name='amigo',
            name='Imagens',
            field=models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Imagens'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='ano_fabricacao',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='amigo',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
