# Generated by Django 4.2.5 on 2023-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_rename_imagens_amigo_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='amigo',
            name='info',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='modelo',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo'),
        ),
    ]
